---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3000011932-OOBDK4PTDIkVIX7h55j4hQ1p3tk66ZU192GxtZD
:access_token_secret: ks8XbqOrqXaZAZGSlApUw9nBl1raZ6cL8TSOxuvn7T9jp
